name: Run Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: |
          echo "Muxia Project"
          cat /etc/os-release
      - name: Install python
        run:
          sudo apt install -y python3-pip